# Generated by Django 6.0.3 on 2026-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
