# Generated by Django 6.0.3 on 2026-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_customuser_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited capacity'),
        ),
    ]
