# Generated by Django 6.0.3 on 2026-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='ticket_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
